/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gearman.core.ui;

/**
 *
 * @author bogdan.mocanu
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appStatusPanel = new javax.swing.JPanel();
        appStatusLabel = new javax.swing.JLabel();
        mainContentSplitPane = new javax.swing.JSplitPane();
        leftModulesPanel = new javax.swing.JPanel();
        searchModulesTextField = new javax.swing.JTextField();
        modulesTreeScrollPane = new javax.swing.JScrollPane();
        modulesTree = new javax.swing.JTree();
        openModulesTabbedPane = new javax.swing.JTabbedPane();
        base64Panel = new javax.swing.JPanel();
        appMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        appStatusPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        appStatusLabel.setText("Build 1.0 at Nov/9/2018");

        javax.swing.GroupLayout appStatusPanelLayout = new javax.swing.GroupLayout(appStatusPanel);
        appStatusPanel.setLayout(appStatusPanelLayout);
        appStatusPanelLayout.setHorizontalGroup(
            appStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appStatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appStatusLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        appStatusPanelLayout.setVerticalGroup(
            appStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        mainContentSplitPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 0, 3));
        mainContentSplitPane.setDividerLocation(200);
        mainContentSplitPane.setResizeWeight(0.3);

        searchModulesTextField.setText("Search modules");
        searchModulesTextField.setEnabled(false);

        modulesTreeScrollPane.setViewportView(modulesTree);

        javax.swing.GroupLayout leftModulesPanelLayout = new javax.swing.GroupLayout(leftModulesPanel);
        leftModulesPanel.setLayout(leftModulesPanelLayout);
        leftModulesPanelLayout.setHorizontalGroup(
            leftModulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchModulesTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
            .addComponent(modulesTreeScrollPane)
        );
        leftModulesPanelLayout.setVerticalGroup(
            leftModulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftModulesPanelLayout.createSequentialGroup()
                .addComponent(searchModulesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modulesTreeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
        );

        mainContentSplitPane.setLeftComponent(leftModulesPanel);

        base64Panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 0, 3));

        javax.swing.GroupLayout base64PanelLayout = new javax.swing.GroupLayout(base64Panel);
        base64Panel.setLayout(base64PanelLayout);
        base64PanelLayout.setHorizontalGroup(
            base64PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );
        base64PanelLayout.setVerticalGroup(
            base64PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );

        openModulesTabbedPane.addTab("Base64 codec", base64Panel);

        mainContentSplitPane.setRightComponent(openModulesTabbedPane);

        jMenu1.setText("File");
        appMenuBar.add(jMenu1);

        jMenu2.setText("Edit");
        appMenuBar.add(jMenu2);

        setJMenuBar(appMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appStatusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainContentSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainContentSplitPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appStatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar appMenuBar;
    private javax.swing.JLabel appStatusLabel;
    private javax.swing.JPanel appStatusPanel;
    private javax.swing.JPanel base64Panel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel leftModulesPanel;
    private javax.swing.JSplitPane mainContentSplitPane;
    private javax.swing.JTree modulesTree;
    private javax.swing.JScrollPane modulesTreeScrollPane;
    private javax.swing.JTabbedPane openModulesTabbedPane;
    private javax.swing.JTextField searchModulesTextField;
    // End of variables declaration//GEN-END:variables
}
